def _subs(*names: str) -> list[dict[str, str]]:
    items: list[dict[str, str]] = []
    for name in names:
        slug = "".join(ch.lower() if ch.isalnum() else "-" for ch in name).strip("-")
        while "--" in slug:
            slug = slug.replace("--", "-")
        items.append({"id": slug[:64], "name": name})
    return items


CATEGORIES = [
    {
        "id": "bakery",
        "name": "Cake & Bakery",
        "blurb": "Birthday cakes, cupcakes, and home bakes",
        "image": "/images/cat-bakery.png",
        "subcategories": _subs(
            "Birthday Cakes",
            "Anniversary Cakes",
            "Wedding Cakes",
            "Cupcakes",
            "Bento Cakes",
            "Cheesecakes",
            "Brownies",
            "Cookies",
            "Donuts",
            "Muffins",
            "Other",
        ),
    },
    {
        "id": "painting",
        "name": "Art",
        "blurb": "Paintings, drawings, and custom art",
        "image": "/images/cat-painting.png",
        "subcategories": _subs(
            "Hand Paintings",
            "Portrait Paintings",
            "Canvas Art",
            "Wall Art",
            "Digital Art",
            "Other Art",
        ),
    },
    {
        "id": "crafts",
        "name": "Hand Crafts",
        "blurb": "Pottery, macramé, and homemade gifts",
        "image": "/images/cat-crafts.png",
        "subcategories": _subs(
            "Handmade Decorations",
            "Handmade Cards",
            "Handmade Bags",
            "Handmade Baskets",
            "Handmade Toys",
            "Handmade Dolls",
            "Wooden Crafts",
            "Clay Crafts",
            "Pottery",
            "Resin Crafts",
            "Home Decorations",
            "Handmade Accessories",
            "Custom Crafts",
            "Other Hand Crafts",
        ),
    },
    {
        "id": "jewelry",
        "name": "Jewellery",
        "blurb": "Beaded, brass, and handmade pieces",
        "image": "/images/cat-jewelry.png",
        "subcategories": _subs(
            "Handmade Jewellery",
            "Earrings",
            "Necklaces",
            "Bracelets",
            "Rings",
            "Anklets",
            "Hair Accessories",
            "Jewellery Sets",
            "Kids' Jewellery",
            "Other Jewellery",
        ),
    },
    {
        "id": "cooking",
        "name": "Food",
        "blurb": "Short eats, sweets, and home-cooked meals",
        "image": "/images/cat-cooking.png",
        "subcategories": _subs(
            "Homemade Food",
            "Traditional Food",
            "Snacks",
            "Pickles",
            "Chutneys",
            "Jams",
            "Sauces",
            "Spice Products",
            "Healthy Food",
            "Vegetarian Food",
            "Other Food",
        ),
    },
    {
        "id": "flowers",
        "name": "Flowers",
        "blurb": "Fresh flowers, bouquets, and floral decorations",
        "image": "/images/cat-flowers.png",
        "subcategories": _subs(
            "Fresh Flowers",
            "Flower Bouquets",
            "Hand Bouquets",
            "Wedding Flowers",
            "Bridal Bouquets",
            "Artificial Flowers",
            "Preserved Flowers",
            "Dried Flowers",
            "Flower Arrangements",
            "Floral Decorations",
        ),
    },
    {
        "id": "gifts",
        "name": "Gifts",
        "blurb": "Gift boxes, hampers, and personalized presents",
        "image": "/images/cat-gifts.png",
        "subcategories": _subs(
            "Birthday Gifts",
            "Anniversary Gifts",
            "Wedding Gifts",
            "Valentine's Gifts",
            "Personalized Gifts",
            "Gift Boxes",
            "Gift Hampers",
            "Corporate Gifts",
            "Baby Gifts",
            "Graduation Gifts",
            "Handmade Gifts",
            "Chocolate Gifts",
            "Customized Gifts",
            "Other Gifts",
        ),
    },
    {
        "id": "fashion",
        "name": "Fashion",
        "blurb": "Clothes, bags, and wearable pieces",
        "image": "/images/cat-fashion.png",
        "subcategories": _subs(
            "Women's Clothing",
            "Men's Clothing",
            "Kids' Clothing",
            "Dresses",
            "Sarees",
            "Blouses",
            "T-Shirts",
            "Shirts",
            "Trousers",
            "Skirts",
            "Traditional Wear",
            "Bridal Wear",
            "Baby Clothing",
            "Handmade Clothing",
            "Custom Clothing",
            "Bags",
            "Handbags",
            "Wallets",
            "Scarves",
            "Fashion Accessories",
            "Hair Accessories",
            "Other Fashion",
        ),
    },
    {
        "id": "health-beauty",
        "name": "Health & Beauty",
        "blurb": "Makeup, hair, nails, and beauty treatments",
        "image": "/images/cat-health-beauty.png",
        "subcategories": _subs(
            "Makeup Artists",
            "Bridal Makeup",
            "Hair Styling",
            "Hairdressing",
            "Nail Services",
            "Nail Art",
            "Eyelash Services",
            "Skincare",
            "Facial Services",
            "Beauty Treatments",
            "Spa Services",
            "Mehendi",
            "Beauty Products",
        ),
    },
    {
        "id": "health-wellness",
        "name": "Health & Wellness",
        "blurb": "Herbal, Ayurvedic, oils, and natural care",
        "image": "/images/cat-health-wellness.png",
        "subcategories": _subs(
            "Herbal Products",
            "Ayurvedic Products",
            "Natural Products",
            "Wellness Products",
            "Personal Care",
            "Bath & Body Products",
            "Aromatherapy",
            "Essential Oils",
            "Other Health & Beauty",
        ),
    },
    {
        "id": "other",
        "name": "Other",
        "blurb": "Anything that does not fit the groups above",
        "image": "/images/cat-other.png",
        "subcategories": _subs("Other"),
    },
]

CITIES = [
    "Western Province",
    "Central Province",
    "Southern Province",
    "Northern Province",
    "Eastern Province",
    "North Western Province",
    "North Central Province",
    "Uva Province",
    "Sabaragamuwa Province",
]


def category_by_id(category_id: str) -> dict | None:
    return next((item for item in CATEGORIES if item["id"] == category_id), None)


def subcategory_ids(category_id: str) -> set[str]:
    category = category_by_id(category_id)
    if not category:
        return set()
    return {item["id"] for item in category.get("subcategories") or []}
